### ISSUE TITLE
Dispatcher errors

### ISSUE THREAD

**Issue by Koyamie** [discordjs/discord.js#2317]
**Please describe the problem you are having in as much detail as possible:**
Having lot of times issues with dispatcher.

First one : 
```js
TypeError: Cannot read property 'send' of null
at StreamDispatcher._sendPacket (/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:244:47)
```
This occurs as an Unaught Exception and on StreamDispatcher._write

Second one : 
```js
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:237:12)
    at StreamDispatcher.Writable.write (_stream_writable.js:287:5)
    at StreamDispatcher.Writable.end (_stream_writable.js:573:10)
```
This one occurs when using <StreamDispatcher>.end() function

Last one : 
```js
TypeError: cb is not a function
    at afterWrite (_stream_writable.js:474:3)
    at onwrite (_stream_writable.js:465:7)
    at StreamDispatcher.resume (/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:142:35)
```
Occurs when using the <StreamDispatcher>.resume() function.

**Include a reproducible code sample here, if possible:**
```js
const dispatcher = <VoiceConnection>.play(stream);
// [...]
dispatcher.end(); // Second error, happening randomly
// [...]
dispatcher.pause();
dispatcher.resume(); // Last error, happening randomly too
```

**Further details:**

- discord.js version: master
- node.js version: 9.4.0
- Operating system: debian 9
- Priority this issue should have – please be realistic and elaborate if possible: 

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by CatsMiaow** [comment]
node.js 8.9.4
discord.js: master 2018-02-13
os: CentOS 7

Occurs even after a StreamDispatcher error.
```bash
2018-02-14 06:49:11: Error: input stream: The uploader has not made this video available in your country.
    at request (/home/tested/discord-bot/node_modules/ytdl-core/lib/info.js:64:25)
    at IncomingMessage.res.on (/home/tested/discord-bot/node_modules/miniget/lib/index.js:75:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2018-02-14 06:49:12: 
/home/tested/discord-bot/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:244
      this.player.voiceConnection.sockets.udp.send(packet)
                                              ^
TypeError: Cannot read property 'send' of null
    at StreamDispatcher._sendPacket (/home/tested/discord-bot/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:244:47)
    at StreamDispatcher._playChunk (/home/tested/discord-bot/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:215:10)
    at StreamDispatcher._write (/home/tested/discord-bot/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:104:10)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at StreamDispatcher.Writable.write (_stream_writable.js:290:11)
    at Encoder.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Encoder.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Encoder.Readable.push (_stream_readable.js:208:10)
    at Encoder.Transform.push (_stream_transform.js:147:32)
    at Encoder._transform (/home/tested/discord-bot/node_modules/discord.js/node_modules/prism-media/src/transcoders/Opus.js:105:12)
    at Encoder.Transform._read (_stream_transform.js:186:10)
    at Encoder.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Encoder.Writable.write (_stream_writable.js:290:11)
    at VolumeTransformer16LE.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at VolumeTransformer16LE.emit (events.js:211:7)
```

**Comment by hydrabolt** [comment]
I resolved the first issue (`Cannot read property 'send' of null`) in https://github.com/discordjs/discord.js/commit/8289b70e2c92761aff682a19d0ade81ca09fd177, I'm assuming the issue is a bad connection.

**Comment by hydrabolt** [comment]
Third issue (`TypeError: cb is not a function`) resolved in https://github.com/discordjs/discord.js/commit/79b02dd35ff99113395fb476deb2dab5c6b05b4b, I couldn't reproduce it but I still applied a patch that should work.

**Comment by hydrabolt** [comment]
The final issue is because you're using `dispatcher.end()` instead of `dispatcher.destroy()` -- please switch it!

If your errors are fixed after these commits and that change, please close this issue.

**Comment by CatsMiaow** [comment]
same issue.

```bash
2018-03-13 16:27:56: Error: input stream: No formats found with custom filter
    at Object.exports.chooseFormat (/home/tested/discord-bot/node_modules/ytdl-core/lib/util.js:116:14)
    at downloadFromInfoCallback (/home/tested/discord-bot/node_modules/ytdl-core/lib/index.js:62:21)
    at getInfo (/home/tested/discord-bot/node_modules/ytdl-core/lib/index.js:25:5)
    at util.parallel (/home/tested/discord-bot/node_modules/ytdl-core/lib/info.js:222:11)
    at Object.exports.parallel (/home/tested/discord-bot/node_modules/ytdl-core/lib/util.js:462:5)
    at sig.getTokens (/home/tested/discord-bot/node_modules/ytdl-core/lib/info.js:201:14)
    at Object.exports.getTokens (/home/tested/discord-bot/node_modules/ytdl-core/lib/sig.js:29:5)
    at request (/home/tested/discord-bot/node_modules/ytdl-core/lib/info.js:179:11)
    at IncomingMessage.res.on (/home/tested/discord-bot/node_modules/miniget/lib/index.js:75:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) - /command/action/music.ts:304
2018-03-13 16:27:58: 
/home/tested/discord-bot/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:246
      this.player.voiceConnection.sockets.udp.send(packet)
                                              ^
TypeError: Cannot read property 'send' of null
    at StreamDispatcher._sendPacket (/home/tested/discord-bot/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:246:47)
    at StreamDispatcher._playChunk (/home/tested/discord-bot/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:214:10)
    at StreamDispatcher._write (/home/tested/discord-bot/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:104:10)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at StreamDispatcher.Writable.write (_stream_writable.js:290:11)
    at Encoder.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Encoder.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Encoder.Readable.push (_stream_readable.js:208:10)
    at Encoder.Transform.push (_stream_transform.js:147:32)
    at Encoder._transform (/home/tested/discord-bot/node_modules/prism-media/src/transcoders/Opus.js:113:12)
    at Encoder.Transform._read (_stream_transform.js:186:10)
    at Encoder.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Encoder.Writable.write (_stream_writable.js:290:11)
    at VolumeTransformer16LE.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at VolumeTransformer16LE.emit (events.js:211:7)
```

StreamDispatcher.js:246:47
![image](https://user-images.githubusercontent.com/1300172/37331833-71b373d2-26e8-11e8-873d-15729ad59944.png)

**Comment by hydrabolt** [comment]
The latest commit https://github.com/discordjs/discord.js/commit/ef8366d189b8c53f4acdc279caaae9fe682d63f2 should fix this, if you can test again that'd be great

**Comment by hydrabolt** [comment]
I'm going to assume this issue has been fixed for you, if it hasn't please reopen!

**Comment by Koyamie** [comment]
Heyo, reopening because this error still happens in lastest master.
```js
TypeError: cb is not a function
at afterWrite (_stream_writable.js:477:3)
at onwrite (_stream_writable.js:468:7)
at StreamDispatcher.resume (/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:144:57)
```

**Sample code :**
```js
const dispatcher = <VoiceConnection>.play(stream);
dispatcher.resume();
```

**Comment by appellation** [comment]
@Koyamie you forgot to actually reopen the issue

**Comment by KingDGrizzle** [comment]
@appellation if a collaborator or above closes the issue the submitter cannot re-open it. It is up to a collaborator or above to do it. :)

**Comment by Koyamie** [comment]
@appellation yeah noticed after writing that i couldnt open the issue

**Comment by hydrabolt** [comment]
This seems fixed in the latest master now, can you confirm?

**Comment by amishshah** [comment]
I'll assume it's fixed for now, if it's not please re-open the issue :+1:
