### ISSUE TITLE
Speaking status never ends

### ISSUE THREAD

**Issue by ledlamp** [discordjs/discord.js#3376]
**Please describe the problem you are having in as much detail as possible:**
When streaming anything to a voice channel using StreamDispatcher (i.e. using `playFile()`, `playPCMStream()`, or `playOpusStream()`), the speaking status in the voice channel never ends, even though the dispatcher's speaking status changes to false.

**Include a reproducible code sample here, if possible:**
```js
const TOKEN = "paste_a_bot_token_here";
const VOICE_CHANNEL_ID = "paste_a_voice_channel_id_here";

var Discord = require("discord.js");
var client = new Discord.Client();
client.login(TOKEN);
client.once("ready", () => {
	client.channels.get(VOICE_CHANNEL_ID).join().then(connection => {
		var dispatcher = connection.playFile("test.wav");
		dispatcher.on("speaking", status => console.log("speaking", status));
	});
});
```

**Further details:**
- discord.js version: 11.5.1
- Node.js version: 12.2.0
- Operating system: Windows 7 Ultimate x64
- Priority this issue should have – please be realistic and elaborate if possible: Medium, it's probably an annoying issue for anyone using their bot in voice channels.

- [x] I have also tested the issue on latest master, commit hash: 651ff81bd522c03b5c9724a3a8c14eeb88dcd6b9
Issue is NOT present in latest master. (replace `playFile` with `play` in example code)

**Comment by Fyk0** [comment]
> I have also tested the issue on latest master, commit hash: 651ff81
> Issue is NOT present in latest master. (replace playFile with play in example code)

Fixed on master.

**Comment by KamiKoroshi** [comment]
This still happens.
It only fires the speaking event once per person.

**Comment by Fyko** [comment]
> This still happens.
> It only fires the speaking event once per person.
> 
> I am on linux, ubuntu 18.04
> Latest node version

https://github.com/discordjs/discord.js/issues/3591#issuecomment-558207241

**Comment by KamiKoroshi** [comment]
> 
> 
> > This still happens.
> > It only fires the speaking event once per person.
> > I am on linux, ubuntu 18.04
> > Latest node version
> 
> [#3591 (comment)](https://github.com/discordjs/discord.js/issues/3591#issuecomment-558207241)

Yeah, I saw it after commenting here.
Sucks that it doesnt work...

**Comment by iCrawl** [comment]
With the upcoming v12 release I see this as fixed.
