### ISSUE TITLE
[GUILD_CHANNEL_ORPHAN]: Could not find a parent to this guild channel.

### ISSUE THREAD

**Issue by Tricky-Ricky** [discordjs/discord.js#4005]
**Please describe the problem you are having in as much detail as possible:**
Created a category and channel on the guildCreate event, set the channel parent to the category and tried to lockPermissions(), It failed saying it could not find a parent to this guild channel.
It does put the channel as a child to the category as can be seen here:
![image](https://user-images.githubusercontent.com/36576579/77841220-3f046e00-7187-11ea-869e-514ae790935b.png)
But when it comes to locking permissions, It fails.
**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```
`let modRole = await guild.roles.cache.find(r => r.name === 'Moderator');    
    // Check for logs channel - If not found, create it!
    const staffArea = guild.channels.cache.find(channel => channel.name === 'Staff Area');
    if(!staffArea){
       try {
           guild.channels.create('Staff Area', {
               type : 'category',
               topic : 'Staff Area',
               permissionOverwrites : [{
                id : modRole.id,
                allow : ['VIEW_CHANNEL', 'READ_MESSAGE_HISTORY', 'SEND_MESSAGES', 'MANAGE_MESSAGES','EMBED_LINKS', 'ATTACH_FILES']
               },
               {
                id : guild.id,
                deny : ['VIEW_CHANNEL']
                }],
           })
           console.log('Staff Area created!');
       } catch (error){
        console.log(error)
       }
    }
    const modLogs = await guild.channels.cache.find(channel => channel.name === 'modlogs');
    if(!modLogs){
        try{
            guild.channels.create('modlogs', {
                type: 'text',
                topic: 'Logs Channel'
            }).then(async channel => {
             let staff = guild.channels.cache.find(c => c.name == "Staff Area" && c.type == "category");
             if (!staff){
                 console.log("Staff Area not found!");
             }
             await channel.setParent(staff.id)
             await channel.lockPermissions()
             console.log("Staff area built and roles assigned");
             })
         }
        catch (error){
            console.log(error)
        }
    }`
**Further details:**
I believe this may be due to the API not updating properly, as can be seen in this report:
[https://github.com/discordjs/discord.js/issues/2644](2644)

- discord.js version: v12
- Node.js version: V12.13.1
- Operating system: Windows 10 Dev | Ubuntu Production
- Priority this issue should have – please be realistic and elaborate if possible:
Unsure, but if your not able to lockPermissions() after setParent() then it should be specified

- [] I have also tested the issue on latest master, commit hash:

**Comment by sbaliq** [comment]
Can you `await channel.setParent(staff.id).then(x => {
console.log("Parent set!")
x.lockPermissions()
}).catch(err => {
console.log("An error occured.")
})`

**Comment by uhKevinMC** [comment]
This issue is caused by the aforementioned issue listed above, as the command is executing faster than the bot updating the cache by gateway events. A simple solution would be using the `setTimeout()` method provided by the Client structure.

**Comment by Tricky-Ricky** [comment]
> Can you try `await channel.setParent(staff.id).then(x => { console.log("Parent set!") x.lockPermissions() }).catch(err => { console.log("An error occured.") })`

That worked no errors, I presume it's not a bug but more down to my logic?

**Comment by SketchyLxve** [comment]
Unable to reproduce this with the sample shown below.
```js
    message.guild.channels.create("test-channel", {
      type: 'text',
      topic: 'Used for testing'
    })
    .then(async (channel) => {

      const parent = await message.guild.channels.create("parent-for-testing", {
         type: 'category' ,
         permissionOverwrites: [
           {
             id: message.guild.id,
             allow: ['VIEW_CHANNEL', 'SEND_MESSAGES'],
             deny: ['ADD_REACTIONS']
           }
         ]
       });

      await channel.setParent(parent.id);
      await channel.lockPermissions();
    })
```

**Comment by Tricky-Ricky** [comment]
@SketchyLxve Interesting, create the channel and then the category would avoid this...

**Comment by Tricky-Ricky** [comment]
Will close this, as it's been resolved by the code provided by @sbaliq and also a non-reproducable version by @SketchyLxve therefore most likely down to my code.

**Comment by SketchyLxve** [comment]
I've got a quick question, @Tricky-Ricky, what if you roll back to some version like v12.0.1? Does the issue still persist? Or is it just present for you on v12.1.1?

**Comment by Tricky-Ricky** [comment]
The above error happens with my code on v12.0.1 - But again the code from @sbaliq works in v12.0.1

**Comment by uhKevinMC** [comment]
That is because the value you defined channel as does not change when you use the `.setParent()` method. 
Resolving the promise using `.then()` returns the modified/patched clone of the channel.

Not much we can do PR wise as this would be considered a breaking change, so you can suggest this again once v13 is ready for PR's and such.
