### ISSUE TITLE
Emoji#identifier should be consistent with EmojiIdentifierResolvable

### ISSUE THREAD

**Issue by pettinen** [discordjs/discord.js#5086]
This issue concerns only custom, non-animated emoji. It's present at `9f3c3e0` on `master`.

`Emoji#identifier` and `GuildEmojiManager#resolveIdentifier` return a string of the form `name:id`. This value could ideally be used as an `EmojiIdentifierResolvable`, but cannot as documented, as `EmojiIdentifierResolvable` must start with a colon (`:name:id`). Although the docs seem to be wrong in this regard; it seems `EmojiIdentifierResolvable`s are always parsed by `Util#parseEmoji`, which accepts the `name:id` form just fine.

So, my recommendations:
1. Add `name:id` and `<name:id>` to the documented accepted forms of `EmojiIdentifierResolvable` (in the spirit of Postel's law)
2. Update `Emoji#identifier` and `GuildEmojiManager#resolveIdentifier` to return a colon-prefixed value

My argument for (2) is consistency: for animated emoji, `Emoji#identifier` is exactly the string between the `< >` in messages, whereas non-animated custom emoji lack the first colon.

Obviously (2) is a breaking change, which should be implemented in a major version bump (if at all; it's not a critical inconsistency, but I'd imagine it might help with e.g. message parsing).

**Comment by Vaporox** [comment]
It is already documented as `name:id`, not `:name:id`

https://github.com/discordjs/discord.js/blob/master/src/managers/BaseGuildEmojiManager.js#L54

**Comment by pettinen** [comment]
> It is already documented as `name:id`, not `:name:id`
> 
> https://github.com/discordjs/discord.js/blob/master/src/managers/BaseGuildEmojiManager.js#L54

Yeah, sorry, I was reading the stable docs, and only checked point (2) (which still stands, albeit with less weight) in the master branch.

**Comment by almostSouji** [comment]
I'm not sure what you mean with (2) or where the benefit in that lies?

**Comment by pettinen** [comment]
Just throwing it out there that I feel there's an inconsistency. But like I said, probably not worth changing and breaking things.

And (1) was already fixed in master (again, my bad), though a more comprehensive phrasing for
https://github.com/discordjs/discord.js/blob/master/src/managers/BaseGuildEmojiManager.js#L54 would be
```
* * The `a:name:id`, `:name:id` or `name:id` emoji identifier string (optionally enclosed in angle brackets) of an emoji
```

**Comment by almostSouji** [comment]
still not sure what you mean, sorry!

- `name:id` is the specification for non-animated emojis
- `a:name.Id` is the specification for animated emoji

those are the values we resolve to in order to URL encode and call the respective rest API route [`PUT /channels/{channel.id}/messages/{message.id}/reactions/{emoji}/@me` ](https://discord.com/developers/docs/resources/channel#create-reaction)

**Comment by pettinen** [comment]
Oh, it's fine if it's what the API uses. I thought it was inconsistent since non-animated emoji are represented in messages as `<:name:id>`.
